trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /dependency/dependency-ex2.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: Dev
  jobs:
   - job: Job1
     displayName: First Job
     continueOnError: true
     workspace:
      clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

   - job: Job2
     displayName:  Second Job
     continueOnError: true
     workspace:
       clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

- stage: QA
  dependsOn: Dev
  condition: succeeded('Dev')
  jobs:
   - job: Job1
     displayName: First Job
     continueOnError: true
     workspace:
      clean: outputs
     steps:
     - script: echo hello step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

   - job: Job2
     displayName:  Second Job
     continueOnError: true
     workspace:
       clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: Hi step 2
  
- stage: UAT
  dependsOn: QA
  condition: succeeded('QA')
  jobs:
   - job: Job1
     displayName: First Job
     continueOnError: true
     workspace:
      clean: outputs
     steps:
     - script: echo qa step 1 
       displayName: step 1
     - script: echo hi qa step 2 
       displayName: step 2

   - job: Job2
     displayName:  Second Job
     continueOnError: true
     workspace:
       clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo qa step 2 
       displayName: step 2
- stage: Prepod
  jobs:
   - job: Job1
     displayName: First Prepod Job
     continueOnError: true
     workspace:
      clean: outputs
     steps:
     - script: echo Prepod step 1 
       displayName: step 1
     - script: echo Prepod step 2 
       displayName: step 2
- stage: Production
  dependsOn: Prepod
  condition: notsucceeded('Prepod')
  jobs:
   - job: Job1
     displayName: First Job
     continueOnError: true
     workspace:
      clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

